# Generated by Django 4.2.29 on 2026-03-14 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='home_date_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='homemember',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='member',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
