# Generated by Django 4.2.29 on 2026-03-14 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_api', '0002_alter_home_home_date_created_alter_homemember_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='home_date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
