# Generated by Django 4.2.29 on 2026-03-14 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_api', '0003_alter_home_home_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homemember',
            name='role',
            field=models.CharField(max_length=12),
        ),
    ]
