# Generated by Django 4.2.11 on 2026-03-18 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iot_api', '0004_alter_homemember_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='home',
        ),
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=100)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iot_api.home')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='iot_api.room'),
        ),
    ]
